"""Build train/val splits for detection without touching the pinned export.

The Roboflow export ships a 70/20/10 train/valid/test split (1858/531/266). This
project does not test on still images - the combined detection+tracking models are
what get tested - so the test split is dead weight that could be training data
instead.

Rather than moving files (which would break scripts/verify_data.py, since it fails
on both missing and extra files under Datasets/), this script writes the splits as
*lists* into data/splits/. Datasets/ stays byte-identical to the pinned export.

The YOLO and COCO exports use identical filenames, so one assignment drives both
formats and the two model families train on exactly the same images.

Usage:
    python scripts/make_splits.py                  # merge test into train -> 80/20
    python scripts/make_splits.py --val-frac 0.15  # re-split all 2655 -> 85/15
    python scripts/make_splits.py --seed 1         # different re-split draw

Outputs (all outside Datasets/):
    data/roco_central.yaml        Ultralytics data config -> point train.py at this
    data/splits/train.txt         absolute image paths, one per line
    data/splits/val.txt
    data/splits/coco_train.json   merged + re-indexed COCO annotations
    data/splits/coco_val.json
    data/splits/assignment.csv    filename,orig_split,new_split (provenance)
"""

from __future__ import annotations

import argparse
import csv
import json
import random
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
YOLO_DIR = ROOT / "Datasets" / "DJI ROCO Central.v1i.yolov11"
COCO_DIR = ROOT / "Datasets" / "DJI ROCO Central.v1i.coco"
OUT_DIR = ROOT / "data" / "splits"
YAML_PATH = ROOT / "data" / "roco_central.yaml"

ORIG_SPLITS = ("train", "valid", "test")
# Index order must match the export's data.yaml `names` list.
CLASS_NAMES = ["armor", "base", "car", "ignore", "watcher"]


def collect_images() -> dict[str, str]:
    """Map each image filename to the original split folder it lives in."""
    origin: dict[str, str] = {}
    for split in ORIG_SPLITS:
        img_dir = YOLO_DIR / split / "images"
        if not img_dir.is_dir():
            sys.exit(f"Missing {img_dir}. Run: python scripts/download_data.py")
        for img in img_dir.iterdir():
            if img.suffix.lower() in {".jpg", ".jpeg", ".png"}:
                if img.name in origin:
                    sys.exit(f"Duplicate filename across splits: {img.name}")
                origin[img.name] = split
    if not origin:
        sys.exit(f"No images found under {YOLO_DIR}")
    return origin


def assign(origin: dict[str, str], val_frac: float | None, seed: int) -> dict[str, str]:
    """Decide the new split for every image.

    val_frac None  -> keep the export's own valid split, fold test into train.
    val_frac F     -> pool all images and draw a fresh validation set of size F.
    """
    if val_frac is None:
        return {
            name: ("val" if split == "valid" else "train")
            for name, split in origin.items()
        }

    if not 0.0 < val_frac < 1.0:
        sys.exit(f"--val-frac must be strictly between 0 and 1, got {val_frac}")

    names = sorted(origin)  # sorted first so the seed alone determines the draw
    random.Random(seed).shuffle(names)
    n_val = round(len(names) * val_frac)
    val = set(names[:n_val])
    return {name: ("val" if name in val else "train") for name in origin}


def class_counts(names: list[str], origin: dict[str, str]) -> Counter[str]:
    """Count labelled instances per class, read from the YOLO label files."""
    counts: Counter[str] = Counter()
    for name in names:
        label = YOLO_DIR / origin[name] / "labels" / f"{Path(name).stem}.txt"
        if not label.is_file():
            continue
        for line in label.read_text(encoding="utf-8").splitlines():
            if line.strip():
                counts[CLASS_NAMES[int(line.split()[0])]] += 1
    return counts


def write_image_lists(split_names: dict[str, list[str]], origin: dict[str, str]) -> None:
    """Write one absolute image path per line.

    Ultralytics derives label paths by swapping /images/ for /labels/, so pointing
    into the original split folders resolves labels correctly with no copying.
    """
    for split, names in split_names.items():
        lines = [
            (YOLO_DIR / origin[name] / "images" / name).as_posix() for name in names
        ]
        out = OUT_DIR / f"{'train' if split == 'train' else 'val'}.txt"
        out.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_yaml() -> None:
    YAML_PATH.write_text(
        "# Generated by scripts/make_splits.py - do not hand-edit.\n"
        "# Detection split with the export's test set folded into train; the\n"
        "# combined detection+tracking models are what get held-out tested.\n"
        f"path: {YOLO_DIR.as_posix()}\n"
        f"train: {(OUT_DIR / 'train.txt').as_posix()}\n"
        f"val: {(OUT_DIR / 'val.txt').as_posix()}\n"
        "\n"
        "names:\n"
        + "".join(f"  {i}: {n}\n" for i, n in enumerate(CLASS_NAMES)),
        encoding="utf-8",
    )


def write_coco(split_names: dict[str, list[str]], origin: dict[str, str]) -> None:
    """Merge the per-split COCO files, re-indexing ids so they cannot collide.

    Every split's export numbers its images and annotations from 0, so a naive
    concatenation would silently alias annotations onto the wrong images. file_name
    keeps a split-relative prefix, so load with root=Datasets/DJI ROCO Central.v1i.coco.
    """
    source = {}
    for split in ORIG_SPLITS:
        path = COCO_DIR / split / "_annotations.coco.json"
        if not path.is_file():
            sys.exit(f"Missing {path}")
        source[split] = json.loads(path.read_text(encoding="utf-8"))

    categories = source["train"]["categories"]
    for split in ORIG_SPLITS:
        if source[split]["categories"] != categories:
            sys.exit(f"Category list in {split} differs from train - cannot merge.")

    # image_id -> annotations, per original split, so lookup stays O(1).
    by_image = {
        split: _group(data["annotations"]) for split, data in source.items()
    }
    id_by_name = {
        split: {img["file_name"]: img["id"] for img in data["images"]}
        for split, data in source.items()
    }

    for split, names in split_names.items():
        images, annotations = [], []
        for new_id, name in enumerate(names):
            orig = origin[name]
            old_id = id_by_name[orig].get(name)
            if old_id is None:
                sys.exit(f"{name} is missing from the {orig} COCO annotations.")
            img = dict(next(i for i in source[orig]["images"] if i["id"] == old_id))
            img["id"] = new_id
            img["file_name"] = f"{orig}/{name}"
            images.append(img)
            for ann in by_image[orig].get(old_id, []):
                ann = dict(ann)
                ann["id"] = len(annotations)
                ann["image_id"] = new_id
                annotations.append(ann)

        merged = {
            "info": source["train"]["info"],
            "licenses": source["train"]["licenses"],
            "categories": categories,
            "images": images,
            "annotations": annotations,
        }
        out = OUT_DIR / f"coco_{'train' if split == 'train' else 'val'}.json"
        out.write_text(json.dumps(merged), encoding="utf-8")


def _group(annotations: list[dict]) -> dict[int, list[dict]]:
    grouped: dict[int, list[dict]] = {}
    for ann in annotations:
        grouped.setdefault(ann["image_id"], []).append(ann)
    return grouped


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--val-frac",
        type=float,
        default=None,
        help="Re-split all images to this validation fraction (e.g. 0.15). "
        "Omit to keep the export's valid split and just fold test into train.",
    )
    parser.add_argument("--seed", type=int, default=0, help="Re-split RNG seed.")
    args = parser.parse_args()

    origin = collect_images()
    assignment = assign(origin, args.val_frac, args.seed)

    split_names: dict[str, list[str]] = {"train": [], "val": []}
    for name in sorted(assignment):
        split_names[assignment[name]].append(name)

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    write_image_lists(split_names, origin)
    write_yaml()
    write_coco(split_names, origin)

    with (OUT_DIR / "assignment.csv").open("w", newline="", encoding="utf-8") as fh:
        writer = csv.writer(fh)
        writer.writerow(["filename", "orig_split", "new_split"])
        for name in sorted(assignment):
            writer.writerow([name, origin[name], assignment[name]])

    total = len(assignment)
    mode = "merge test into train" if args.val_frac is None else f"re-split seed={args.seed}"
    print(f"{total} images  ({mode})")
    for split in ("train", "val"):
        names = split_names[split]
        counts = class_counts(names, origin)
        share = 100 * len(names) / total
        print(f"  {split:<5} {len(names):>5} images ({share:4.1f}%)  "
              f"{sum(counts.values()):>6} instances  "
              + "  ".join(f"{c}={counts[c]}" for c in CLASS_NAMES))
    print(f"\nwrote {YAML_PATH.relative_to(ROOT)} and {OUT_DIR.relative_to(ROOT)}/")
    print("Datasets/ untouched - `python scripts/verify_data.py` should still pass.")


if __name__ == "__main__":
    main()
