#!/usr/bin/env bash
# Four trackers, identical input, identical clips and frame count.
#
# DETECTOR-FED, NOT GROUND-TRUTH-FED. Feeding trackers the reference boxes is degenerate
# here: the ground truth is itself machine-generated by association, so a Kalman tracker
# handed those boxes simply returns the labeller's own tracks. Measured, not assumed -
# gt-fed on arc01 scored classical 0.9917 and sort 0.9917, identical to six decimal
# places, which is not two trackers agreeing but one answer arrived at twice.
#
# Detector-fed asks a real question instead: how much an online tracker loses against an
# offline reference that saw the whole clip. It is also the protocol the existing 7-clip
# rows already use, so these rows extend that table rather than forming a parallel one.
#
# 150 frames, 3 clips: GOTURN runs at seconds per frame, so the full 7x300 protocol would
# take ~17 hours. Latency is not what is measured here, and MOTA over 450 frames still
# separates the trackers.
set -u
PY=.venv/Scripts/python.exe
LIMIT=150
DET=runs/detect/yolo_960/weights/best.pt
for seq in arc01 arc02 arc05; do
  for trk in classical sort vit goturn; do
    # Stopping this cleanly matters: killing the driver does not reliably take
    # the child down on Windows, and a survivor writing to the same results CSV
    # as its replacement produces two runs' rows interleaved in one file.
    if [ -f STOP ]; then echo 'STOP found - exiting cleanly'; exit 0; fi
    out="results/tracking/h2h/${seq}"
    echo "=== ${seq} / ${trk} ==="
    $PY scripts/run_trackers.py --seq "data/tracking/${seq}" --tracker "$trk" \
        --detector "$DET" --limit "$LIMIT" --out "$out" 2>&1 | tail -3
    res="${out}/${trk}_det.txt"
    if [ -f "$res" ]; then
      $PY scripts/eval_tracking.py --seq "data/tracking/${seq}" --results "$res" \
          --name "${trk}_det150" --max-frame "$LIMIT" --bootstrap 500 2>&1 | tail -9
    else
      echo "!! no results at ${res}"; ls "$out" 2>/dev/null
    fi
  done
done
